export const defaultUseQueryOptions = {
  staleTime: 1000 * 60 * 5,
  retry: false,
};

export const QUERY_KEY = Object.freeze({
  ACCOUNT_PROJECTS: "projects/accounts",
  USER_PROJECTS: "projects/account-users",
  ACCOUNT_PROJECT: "account-project",
  SUBMISSION_PACKAGE: "package",
  ACCOUNT_USER: "user",
  SUBMISSION_ITEM: "item",
  PROJECTS: "projects",
  SUBMISSIONS: "submissions",
  USERS: "users",
  PACKAGE_VERSIONS: "package-versions",
  STAFF_USER: "staff-user",
  ACTIVITY_LOGS: "activity-logs",
  SUBMISSION_VERSIONS: "submission-versions",
  INVITATION: "invitation",
  ACCOUNT_USERS: "account-users",
  PROPONENTS: "proponents",
  PROPONENT: "proponent",
  USER_ACCOUNT_DATA: "user-account-data",
  FAILED_SUBMISSIONS: "failed-submissions",
  TERMS_OF_SERVICE: "terms-of-service",
  PACKAGE_DOCUMENT_SUBMISSIONS: "package-document-submissions",
  ACCOUNT_SUBMISSION_PACKAGES: "account-submission-packages",
  GEO_UPLOADS: "geo/uploads",
});
